Repository brixion/.github, pull requests merged in 2025-08, with the labels that each got.

#9 👷 Add a reusable workflow for labels sync
  .github/workflows/label-sync.yml
Labels: type: feature

#10 🔥 Remove configuration section from PR templates
  .github/PULL_REQUEST_TEMPLATE/documentation.md
  .github/PULL_REQUEST_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/fix.md
  .github/PULL_REQUEST_TEMPLATE/general-extended.md
  .github/PULL_REQUEST_TEMPLATE/general-small.md
  .github/PULL_REQUEST_TEMPLATE/refactor.md
Labels: type: bug

#11 👷 Use self hosted runners for label-sync workflow
  .github/workflows/label-sync.yml
Labels: type: ci

#16 💄 Add Gitmoji's to type labels to backend
  labels/backend.yml
Labels: type: ci

#14 💄 Add Gitmoji to type labels for better recognizability
  labels/backend.yml
  labels/frontend.yml
  labels/general.yml
Labels: type: ci
